import sys
import re

filepath = r'd:\LICENTA\Licenta DOC\licenta.tex'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Fix Prompt Duplication and Update with Actual Prompt
prompt_duplicate = '''Structura de inginerie a prompt-ului (\\textit{prompt engineering}) utilizată pentru a asigura aderența strictă a modelului la formatul JSON și pentru a impune rolul de bibliotecar este următoarea:

\\begin{lstlisting}[caption={Șablonul de sistem (System Prompt) pentru Mistral-Nemo},label={code:system_prompt}]
You are a specialized librarian and expert book recommender.
You will be provided with a user's reading profile, and a list of candidate books (in JSON format) generated by a mathematical filter.
Your task is to RERANK these candidate books based on deep semantic context, philosophical tone, and the user's nuanced preferences, not just generic genres.

IMPORTANT: The user has already read the following books: [READ_BOOKS]. Do NOT recommend these exact books. If they appear in the candidates list, omit them or rank them at the very bottom.

User Profile: [USER_PROFILE]
Candidates: [CANDIDATES_JSON]

Return your answer as a JSON object containing a single key "recommendations" which is an array, ordered from Most Recommended (index 0) to Least Recommended.
Each object in the array MUST contain exactly two fields: 'id' (the string ID of the book) and 'reasoning' (1 sentence explaining why it fits or misses the user's specific taste).
Output ONLY valid JSON.
\\end{lstlisting}'''

updated_prompt = '''Structura de inginerie a prompt-ului (\\textit{prompt engineering}) utilizată pentru a asigura aderența strictă a modelului la formatul JSON și pentru a impune rolul de bibliotecar este următoarea:

\\begin{lstlisting}[caption={Șablonul de sistem (System Prompt) pentru Mistral-Nemo},label={code:system_prompt}]
You are a specialized librarian and expert book recommender.
You will be provided with a user's reading profile, and a list of candidate books (in JSON format) generated by a mathematical filter.
Your task is to RERANK these candidate books based on deep semantic context, philosophical tone, and the user's nuanced preferences, not just generic genres.
IMPORTANT: The user has already read the following books: {read_books_str}. Do NOT recommend these exact books. If they appear in the candidates list, omit them or rank them at the very bottom.

User Profile: {user_profile}

Candidates:
{candidates_json}

Return your answer as a JSON object containing a single key "recommendations" which is an array, ordered from Most Recommended (index 0) to Least Recommended. 
Each object in the array MUST contain exactly two fields: 'id' (the string ID of the book) and 'reasoning' (1 sentence explaining why it fits or misses the user's specific taste).
Output ONLY valid JSON.
Example output:
{
  "recommendations": [
    {"id": "12345", "reasoning": "Fits the user's love for dark sci-fi."},
    {"id": "67890", "reasoning": "Matches the political betrayal theme."}
  ]
}
\\end{lstlisting}'''

# Replace FIRST occurrence with updated prompt
content = content.replace(prompt_duplicate, updated_prompt, 1)

# Delete SECOND occurrence completely (and any trailing newlines if possible, but simplest is just replacing with empty)
# Let's handle the duplicate text and also any newline right before/after it if possible.
content = content.replace(prompt_duplicate + '\n', '', 1)
content = content.replace(prompt_duplicate, '', 1)


# 2. Fix Acronym List Duplication
acronym_duplicate = '''SPI - Serial Peripheral Interface;
LLM - Large Language Model; \\\\
OTA - Over-The-Air; \\\\
PMIC - Power Management Integrated Circuit; \\\\
SPI - Serial Peripheral Interface;'''

if acronym_duplicate in content:
    content = content.replace(acronym_duplicate, 'SPI - Serial Peripheral Interface;', 1)

# 3. Fix LaTeX Leak
leak_search = '''% (se vor scrie toate prescurtările utilizate in ordine alfabetică)

\\\\noindent 
AI - Artificial Intelligence; \\\\'''

leak_replace = '''% (se vor scrie toate prescurtările utilizate in ordine alfabetică)

AI - Artificial Intelligence; \\\\'''

content = content.replace(leak_search, leak_replace, 1)


# 4. Fix "Al" vs "AI" Typo
content = re.sub(r'Sistemul de administrare(.{1,30})recomandare Al', r'Sistemul de administrare\1recomandare AI', content)
content = re.sub(r'Interfa(.{1,10})asistentului Al', r'Interfa\1asistentului AI', content)
content = re.sub(r'descărcate de asistentul Al', r'descărcate de asistentul AI', content)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print('Fixed properly')
