import json
import ollama
import pandas as pd
from typing import List, Dict

from src.config import OLLAMA_MODEL

class LLMReranker:
    def __init__(self, model_name: str = OLLAMA_MODEL):
        self.model_name = model_name

    def format_candidates(self, candidates_df: pd.DataFrame) -> str:
        """
        Transforms the Top K candidates into a clean text/JSON representation for the LLM.
        """
        candidates_list = []
        for idx, row in candidates_df.iterrows():
            candidates_list.append({
                "id": str(row.get('book_id', row.get('id', ''))),
                "title": row.get('title', 'Unknown'),
                "rating": round(row['average_rating'], 2),
                "tags": row.get('tags', ''),
                "year": row.get('publication_year', ''),
                "pages": row.get('num_pages', ''),
                "image_url": row.get('image_url', ''),
                "description": row['description'][:200] + "..." if isinstance(row['description'], str) else ""
            })
        return json.dumps(candidates_list, indent=2)

    def rerank(self, user_profile: str, candidates_df: pd.DataFrame) -> List[Dict]:
        """
        Sends the user profile and candidate list to Ollama to return a reranked JSON list.
        """
        candidates_json = self.format_candidates(candidates_df)
        
        system_prompt = f"""You are a specialized librarian and expert book recommender.
You will be provided with a user's reading profile, and a list of candidate books (in JSON format) generated by a mathematical filter.
Your task is to RERANK these candidate books based on deep semantic context, philosophical tone, and the user's nuanced preferences, not just generic genres.

User Profile: {user_profile}

Candidates:
{candidates_json}

Return your answer as a raw JSON array, ordered from Most Recommended (index 0) to Least Recommended. 
Each object in the array MUST contain exactly two fields: 'id' (the string ID of the book) and 'reasoning' (1 sentence explaining why it fits or misses the user's specific taste).
Output ONLY valid JSON.
Example output:
[
  {{"id": "12345", "reasoning": "Fits the user's love for dark sci-fi."}},
  {{"id": "67890", "reasoning": "Matches the political betrayal theme."}}
]
"""

        print(f"Querying Ollama ({self.model_name}) for semantic reranking...")
        
        try:
            response = ollama.chat(model=self.model_name, messages=[
              {
                'role': 'system',
                'content': system_prompt
              },
              {
                'role': 'user',
                'content': 'Please provide the reranked JSON list based on my profile.'
              }
            ])
            
            raw_response = response['message']['content']
            
            import re
            
            # Very basic extraction if the LLM adds markdown formatting
            if "```json" in raw_response:
                clean_response = raw_response.split("```json")[1].split("```")[0].strip()
            elif "```" in raw_response:
                clean_response = raw_response.split("```")[1].strip()
            else:
                clean_response = raw_response
                
            try:
                llm_output = json.loads(clean_response)
            except json.JSONDecodeError:
                # Regex fallback: find the first '[' and last ']'
                match = re.search(r'\[.*\]', raw_response, re.DOTALL)
                if match:
                    try:
                        llm_output = json.loads(match.group(0))
                    except json.JSONDecodeError:
                        llm_output = []
                else:
                    llm_output = []
            
            # Robust Merge: The LLM often hallucinates or drops fields (like image_url)
            # or truncates the list early. We must map its reasoning back to the ORIGINAL data!
            original_books = {str(row.get('book_id', row.get('id', ''))): row.to_dict() for _, row in candidates_df.iterrows()}
            final_list = []
            seen_ids = set()
            
            for item in llm_output:
                book_id = str(item.get('id', ''))
                if book_id in original_books and book_id not in seen_ids:
                    merged = original_books[book_id].copy()
                    merged['id'] = book_id
                    # Also fallback title if missing
                    merged['title'] = merged.get('title', item.get('title', 'Unknown'))
                    merged['reasoning'] = item.get('reasoning', '')
                    # ensure image_url is cast to string
                    merged['image_url'] = str(merged.get('image_url', ''))
                    
                    final_list.append(merged)
                    seen_ids.add(book_id)
                    
            # If the LLM stopped generating early (e.g. only 4 books), append the rest!
            for book_id, row_dict in original_books.items():
                if book_id not in seen_ids:
                    merged = row_dict.copy()
                    merged['id'] = book_id
                    merged['image_url'] = str(merged.get('image_url', ''))
                    final_list.append(merged)
                    
            return final_list
            
        except Exception as e:
            print(f"Error during Ollama reranking: {e}")
            print(f"Raw Response: {raw_response if 'raw_response' in locals() else 'None'}")
            
            # Fallback
            fallback = []
            for _, row in candidates_df.iterrows():
                r = row.to_dict()
                r['id'] = str(r['book_id'])
                r['image_url'] = str(r.get('image_url', ''))
                fallback.append(r)
            return fallback
